#pragma once

#define DEVICE_CONTROL_CODE(request,method) \
		CTL_CODE (FILE_DEVICE_UNKNOWN, request, method, FILE_ANY_ACCESS)

#define DEVICE_IOCTL_MATCHENABLE			DEVICE_CONTROL_CODE (0x01, METHOD_BUFFERED)
#define DEVICE_IOCTL_MATCHDISABLE			DEVICE_CONTROL_CODE (0x02, METHOD_BUFFERED)
#define DEVICE_IOCTL_SETRULE   					DEVICE_CONTROL_CODE (0x03, METHOD_BUFFERED)
#define DEVICE_IOCTL_DELRULE   					DEVICE_CONTROL_CODE (0x04, METHOD_BUFFERED)
#define DEVICE_IOCTL_SETLOCALPROXY		DEVICE_CONTROL_CODE (0x05, METHOD_BUFFERED)
#define DEVICE_IOCTL_SETRULECLEAR			DEVICE_CONTROL_CODE (0x06, METHOD_BUFFERED)


/*…Ë÷√*/
typedef struct _DEVICE_IOCTL_SETPROXYINFO
{
	UINT32			uiPID;
	UINT32 			uiTcpPort;
}DEVICE_IOCTL_SETPROXYINFO, *PDEVICE_IOCTL_SETPROXYINFO;









